// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ecommerce.Data;

namespace ecommerce.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("ecommerce.Data.ProductDetails", b =>
                {
                    b.Property<int>("ProductDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioCodec")
                        .HasColumnType("TEXT");

                    b.Property<string>("Backlight")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaterryCells")
                        .HasColumnType("TEXT");

                    b.Property<string>("BatterySize")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bluetooth")
                        .HasColumnType("TEXT");

                    b.Property<string>("CacheSize")
                        .HasColumnType("TEXT");

                    b.Property<string>("CacheType")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardReaderSupport")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardReaderType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChipsetType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpu")
                        .HasColumnType("TEXT");

                    b.Property<string>("CpuSpeed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dimensions")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayResolution")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplaySize")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayTech")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Features")
                        .HasColumnType("TEXT");

                    b.Property<string>("GraphicName")
                        .HasColumnType("TEXT");

                    b.Property<string>("GraphicSize")
                        .HasColumnType("TEXT");

                    b.Property<string>("HardDriveSize")
                        .HasColumnType("TEXT");

                    b.Property<string>("HardDriveType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgUrl1")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgUrl2")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgUrl3")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mainboard")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumCores")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatingSystem")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RamSize")
                        .HasColumnType("TEXT");

                    b.Property<string>("RamSpeed")
                        .HasColumnType("TEXT");

                    b.Property<string>("RamType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sound")
                        .HasColumnType("TEXT");

                    b.Property<string>("Webcam")
                        .HasColumnType("TEXT");

                    b.Property<string>("Weight")
                        .HasColumnType("TEXT");

                    b.Property<string>("WirelessController")
                        .HasColumnType("TEXT");

                    b.Property<string>("WirelessProtocol")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductDetailId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDetails");

                    b.HasData(
                        new
                        {
                            ProductDetailId = 1,
                            AudioCodec = "Realtek ALC3661",
                            Backlight = "Yes",
                            BaterryCells = "6-cell",
                            BatterySize = "91 Wh",
                            Bluetooth = "4.0",
                            CacheSize = "6 MB",
                            CacheType = "L3 cache",
                            CardReaderSupport = "SD Memory Card, SDHC Memory Card, SDIO, SDXC UHS Memory Card",
                            CardReaderType = "3 in 1 card reader",
                            ChipsetType = "Mobile Intel HM87 Express",
                            Cpu = "Intel Core i7 (4th Gen) 4712HQ / 2.3 GHz",
                            CpuSpeed = "3.3 GHz",
                            Dimensions = "15.6 in",
                            DisplayResolution = "3200 x 1800 (QHD+)",
                            DisplaySize = "39.6 cm",
                            DisplayTech = "WLED backlight",
                            DisplayType = "LED QHD+",
                            Features = "Intel Turbo Boost Technology 2.0",
                            GraphicName = "NVIDIA GeForce GT 750M",
                            GraphicSize = "4 GB",
                            HardDriveSize = "1 TB",
                            HardDriveType = "SSD",
                            ImgUrl1 = "https://slickdeals.net/blog/wp-content/uploads/2019/09/19-dell-xps-15-17.jpg",
                            ImgUrl2 = "https://cdn.vox-cdn.com/thumbor/e5o-t8oG4U-dNlsGGfy366O9udU=/1400x1400/filters:format(jpeg)/cdn.vox-cdn.com/uploads/chorus_asset/file/19882265/dims.jpeg",
                            ImgUrl3 = "https://www.slashgear.com/wp-content/uploads/2017/01/Dell13XPSConvertible-980x420.jpg",
                            InputType = "keyboard, touchpad",
                            Mainboard = "Mobile Intel HM87 Express",
                            Manufacturer = "Dell, Inc.",
                            Name = "Dell XPS 15",
                            NumCores = "Quad-Core",
                            OperatingSystem = "Windows 10 64-bit Edition",
                            ProductId = 1,
                            RamSize = "2 x 8 GB",
                            RamType = "DDR3L SDRAM 1600 MHz",
                            Sound = "Stereo speakers, two microphones",
                            Webcam = "15 MPX",
                            Weight = "4.41 lbs",
                            WirelessController = "Intel Dual Band Wireless-AC 7260",
                            WirelessProtocol = "802.11a/b/g/n/ac, Bluetooth 4.0, NFC"
                        },
                        new
                        {
                            ProductDetailId = 2,
                            AudioCodec = "Realtek ALC3661",
                            Backlight = "Yes",
                            BaterryCells = "6-cell",
                            BatterySize = "91 Wh",
                            Bluetooth = "4.0",
                            CacheSize = "6 MB",
                            CacheType = "L3 cache",
                            CardReaderSupport = "SD Memory Card, SDHC Memory Card, SDIO, SDXC UHS Memory Card",
                            CardReaderType = "3 in 1 card reader",
                            ChipsetType = "Mobile Intel HM87 Express",
                            Cpu = "Intel Core i7 (4th Gen) 4712HQ / 2.3 GHz",
                            CpuSpeed = "3.3 GHz",
                            Dimensions = "15.6 in",
                            DisplayResolution = "3200 x 1800 (QHD+)",
                            DisplaySize = "39.6 cm",
                            DisplayTech = "WLED backlight",
                            DisplayType = "LED QHD+",
                            Features = "Intel Turbo Boost Technology 2.0",
                            GraphicName = "NVIDIA GeForce GT 750M",
                            GraphicSize = "4 GB",
                            HardDriveSize = "1 TB",
                            HardDriveType = "SSD",
                            ImgUrl1 = "http://pngimg.com/uploads/macbook/macbook_PNG76.png",
                            ImgUrl2 = "https://9to5mac.com/wp-content/uploads/sites/6/2019/11/16-inch-MacBook-Pro-2019-1.jpg?quality=82&strip=all&w=1600",
                            ImgUrl3 = "https://icdn2.digitaltrends.com/image/digitaltrends/watershed-moment-mac-behance-feat.jpg",
                            InputType = "keyboard, touchpad",
                            Mainboard = "Mobile Intel HM87 Express",
                            Manufacturer = "Dell, Inc.",
                            Name = "Macbook Pro 2020",
                            NumCores = "Quad-Core",
                            OperatingSystem = "Windows 10 64-bit Edition",
                            ProductId = 2,
                            RamSize = "2 x 8 GB",
                            RamType = "DDR3L SDRAM 1600 MHz",
                            Sound = "Stereo speakers, two microphones",
                            Webcam = "15 MPX",
                            Weight = "4.41 lbs",
                            WirelessController = "Intel Dual Band Wireless-AC 7260",
                            WirelessProtocol = "802.11a/b/g/n/ac, Bluetooth 4.0, NFC"
                        },
                        new
                        {
                            ProductDetailId = 3,
                            AudioCodec = "Realtek ALC3661",
                            Backlight = "Yes",
                            BaterryCells = "6-cell",
                            BatterySize = "91 Wh",
                            Bluetooth = "4.0",
                            CacheSize = "6 MB",
                            CacheType = "L3 cache",
                            CardReaderSupport = "SD Memory Card, SDHC Memory Card, SDIO, SDXC UHS Memory Card",
                            CardReaderType = "3 in 1 card reader",
                            ChipsetType = "Mobile Intel HM87 Express",
                            Cpu = "Intel Core i7 (4th Gen) 4712HQ / 2.3 GHz",
                            CpuSpeed = "3.3 GHz",
                            Dimensions = "15.6 in",
                            DisplayResolution = "3200 x 1800 (QHD+)",
                            DisplaySize = "39.6 cm",
                            DisplayTech = "WLED backlight",
                            DisplayType = "LED QHD+",
                            Features = "Intel Turbo Boost Technology 2.0",
                            GraphicName = "NVIDIA GeForce GT 750M",
                            GraphicSize = "4 GB",
                            HardDriveSize = "1 TB",
                            HardDriveType = "SSD",
                            ImgUrl1 = "https://images.idgesg.net/images/article/2019/09/hp_spectre_x360_13_2019_main-100812335-large.jpg",
                            ImgUrl2 = "https://www.windowscentral.com/sites/wpcentral.com/files/styles/large/public/field/image/2019/09/hp-spectre-x360-13-late-2019-2.jpg?itok=hGFrfunO",
                            ImgUrl3 = "https://images-na.ssl-images-amazon.com/images/I/61nWrTKTAFL._AC_SX355_.jpg",
                            InputType = "keyboard, touchpad",
                            Mainboard = "Mobile Intel HM87 Express",
                            Manufacturer = "Dell, Inc.",
                            Name = "HP Spectre X360 15",
                            NumCores = "Quad-Core",
                            OperatingSystem = "Windows 10 64-bit Edition",
                            ProductId = 3,
                            RamSize = "2 x 8 GB",
                            RamType = "DDR3L SDRAM 1600 MHz",
                            Sound = "Stereo speakers, two microphones",
                            Webcam = "15 MPX",
                            Weight = "4.41 lbs",
                            WirelessController = "Intel Dual Band Wireless-AC 7260",
                            WirelessProtocol = "802.11a/b/g/n/ac, Bluetooth 4.0, NFC"
                        },
                        new
                        {
                            ProductDetailId = 4,
                            AudioCodec = "Realtek ALC3661",
                            Backlight = "Yes",
                            BaterryCells = "6-cell",
                            BatterySize = "91 Wh",
                            Bluetooth = "4.0",
                            CacheSize = "6 MB",
                            CacheType = "L3 cache",
                            CardReaderSupport = "SD Memory Card, SDHC Memory Card, SDIO, SDXC UHS Memory Card",
                            CardReaderType = "3 in 1 card reader",
                            ChipsetType = "Mobile Intel HM87 Express",
                            Cpu = "Intel Core i7 (4th Gen) 4712HQ / 2.3 GHz",
                            CpuSpeed = "3.3 GHz",
                            Dimensions = "15.6 in",
                            DisplayResolution = "3200 x 1800 (QHD+)",
                            DisplaySize = "39.6 cm",
                            DisplayTech = "WLED backlight",
                            DisplayType = "LED QHD+",
                            Features = "Intel Turbo Boost Technology 2.0",
                            GraphicName = "NVIDIA GeForce GT 750M",
                            GraphicSize = "4 GB",
                            HardDriveSize = "1 TB",
                            HardDriveType = "SSD",
                            ImgUrl1 = "https://edgeup.asus.com/wp-content/uploads/2016/09/gl702-back-696x464.jpg",
                            ImgUrl2 = "https://edgeup.asus.com/wp-content/uploads/2016/09/gl702-portsleft.jpg",
                            ImgUrl3 = "https://media.karousell.com/media/photos/products/2018/10/27/asus_rog_gl702_strix_1540621749_74d7529a.jpg",
                            InputType = "keyboard, touchpad",
                            Mainboard = "Mobile Intel HM87 Express",
                            Manufacturer = "Dell, Inc.",
                            Name = "ASUS GL702 Gamming",
                            NumCores = "Quad-Core",
                            OperatingSystem = "Windows 10 64-bit Edition",
                            ProductId = 4,
                            RamSize = "2 x 8 GB",
                            RamType = "DDR3L SDRAM 1600 MHz",
                            Sound = "Stereo speakers, two microphones",
                            Webcam = "15 MPX",
                            Weight = "4.41 lbs",
                            WirelessController = "Intel Dual Band Wireless-AC 7260",
                            WirelessProtocol = "802.11a/b/g/n/ac, Bluetooth 4.0, NFC"
                        },
                        new
                        {
                            ProductDetailId = 5,
                            AudioCodec = "Realtek ALC3661",
                            Backlight = "Yes",
                            BaterryCells = "6-cell",
                            BatterySize = "91 Wh",
                            Bluetooth = "4.0",
                            CacheSize = "6 MB",
                            CacheType = "L3 cache",
                            CardReaderSupport = "SD Memory Card, SDHC Memory Card, SDIO, SDXC UHS Memory Card",
                            CardReaderType = "3 in 1 card reader",
                            ChipsetType = "Mobile Intel HM87 Express",
                            Cpu = "Intel Core i7 (4th Gen) 4712HQ / 2.3 GHz",
                            CpuSpeed = "3.3 GHz",
                            Dimensions = "15.6 in",
                            DisplayResolution = "3200 x 1800 (QHD+)",
                            DisplaySize = "39.6 cm",
                            DisplayTech = "WLED backlight",
                            DisplayType = "LED QHD+",
                            Features = "Intel Turbo Boost Technology 2.0",
                            GraphicName = "NVIDIA GeForce GT 750M",
                            GraphicSize = "4 GB",
                            HardDriveSize = "1 TB",
                            HardDriveType = "SSD",
                            ImgUrl1 = "https://target.scene7.com/is/image/Target/GUEST_1f1747c6-1c5c-4df5-839f-e118f52ca133?wid=488&hei=488&fmt=pjpeg",
                            ImgUrl2 = "https://cdn.mos.cms.futurecdn.net/4KtRHLkpg2skF9kmmPwJdV.jpg",
                            ImgUrl3 = "https://www.yangcanggih.com/wp-content/uploads/2019/11/HP-Pavilion-Gaming-15-dk0043tx-8-1200x800.jpg",
                            InputType = "keyboard, touchpad",
                            Mainboard = "Mobile Intel HM87 Express",
                            Manufacturer = "Dell, Inc.",
                            Name = "HP Gamming Pavilion",
                            NumCores = "Quad-Core",
                            OperatingSystem = "Windows 10 64-bit Edition",
                            ProductId = 5,
                            RamSize = "2 x 8 GB",
                            RamType = "DDR3L SDRAM 1600 MHz",
                            Sound = "Stereo speakers, two microphones",
                            Webcam = "15 MPX",
                            Weight = "4.41 lbs",
                            WirelessController = "Intel Dual Band Wireless-AC 7260",
                            WirelessProtocol = "802.11a/b/g/n/ac, Bluetooth 4.0, NFC"
                        },
                        new
                        {
                            ProductDetailId = 6,
                            AudioCodec = "Realtek ALC3661",
                            Backlight = "Yes",
                            BaterryCells = "6-cell",
                            BatterySize = "91 Wh",
                            Bluetooth = "4.0",
                            CacheSize = "6 MB",
                            CacheType = "L3 cache",
                            CardReaderSupport = "SD Memory Card, SDHC Memory Card, SDIO, SDXC UHS Memory Card",
                            CardReaderType = "3 in 1 card reader",
                            ChipsetType = "Mobile Intel HM87 Express",
                            Cpu = "Intel Core i7 (4th Gen) 4712HQ / 2.3 GHz",
                            CpuSpeed = "3.3 GHz",
                            Dimensions = "15.6 in",
                            DisplayResolution = "3200 x 1800 (QHD+)",
                            DisplaySize = "39.6 cm",
                            DisplayTech = "WLED backlight",
                            DisplayType = "LED QHD+",
                            Features = "Intel Turbo Boost Technology 2.0",
                            GraphicName = "NVIDIA GeForce GT 750M",
                            GraphicSize = "4 GB",
                            HardDriveSize = "1 TB",
                            HardDriveType = "SSD",
                            ImgUrl1 = "https://cdn.pocket-lint.com/r/s/1200x/assets/images/148452-laptops-review-acer-swift-7-2019-image1-xusiciqa7b.jpg",
                            ImgUrl2 = "https://i.gadgets360cdn.com/large/acer_swift_7_angle_ndtv_1579179106000.jpg",
                            ImgUrl3 = "https://static.acer.com/up/Resource/Acer/Laptops/Swift_7/Overview/20190312/2019_Swift_7_KSP_5_640.jpg",
                            InputType = "keyboard, touchpad",
                            Mainboard = "Mobile Intel HM87 Express",
                            Manufacturer = "Dell, Inc.",
                            Name = "Acer Swift 7",
                            NumCores = "Quad-Core",
                            OperatingSystem = "Windows 10 64-bit Edition",
                            ProductId = 6,
                            RamSize = "2 x 8 GB",
                            RamType = "DDR3L SDRAM 1600 MHz",
                            Sound = "Stereo speakers, two microphones",
                            Webcam = "15 MPX",
                            Weight = "4.41 lbs",
                            WirelessController = "Intel Dual Band Wireless-AC 7260",
                            WirelessProtocol = "802.11a/b/g/n/ac, Bluetooth 4.0, NFC"
                        },
                        new
                        {
                            ProductDetailId = 7,
                            AudioCodec = "Realtek ALC3661",
                            Backlight = "Yes",
                            BaterryCells = "6-cell",
                            BatterySize = "91 Wh",
                            Bluetooth = "4.0",
                            CacheSize = "6 MB",
                            CacheType = "L3 cache",
                            CardReaderSupport = "SD Memory Card, SDHC Memory Card, SDIO, SDXC UHS Memory Card",
                            CardReaderType = "3 in 1 card reader",
                            ChipsetType = "Mobile Intel HM87 Express",
                            Cpu = "Intel Core i7 (4th Gen) 4712HQ / 2.3 GHz",
                            CpuSpeed = "3.3 GHz",
                            Dimensions = "15.6 in",
                            DisplayResolution = "3200 x 1800 (QHD+)",
                            DisplaySize = "39.6 cm",
                            DisplayTech = "WLED backlight",
                            DisplayType = "LED QHD+",
                            Features = "Intel Turbo Boost Technology 2.0",
                            GraphicName = "NVIDIA GeForce GT 750M",
                            GraphicSize = "4 GB",
                            HardDriveSize = "1 TB",
                            HardDriveType = "SSD",
                            ImgUrl1 = "https://specials-images.forbesimg.com/imageserve/5d690dd768cb0a0008c0dd84/960x0.jpg?cropX1=0&cropX2=1500&cropY1=126&cropY2=1126",
                            ImgUrl2 = "https://www.pngitem.com/pimgs/m/415-4154082_transparent-alienware-laptop-png-dell-alienware-laptops-png.png",
                            ImgUrl3 = "https://www.pcgamesn.com/wp-content/uploads/legacy/Dell_Alienware_17_Intel_Core_i9.jpg",
                            InputType = "keyboard, touchpad",
                            Mainboard = "Mobile Intel HM87 Express",
                            Manufacturer = "Dell, Inc.",
                            Name = "Dell Alienware 17",
                            NumCores = "Quad-Core",
                            OperatingSystem = "Windows 10 64-bit Edition",
                            ProductId = 7,
                            RamSize = "2 x 8 GB",
                            RamType = "DDR3L SDRAM 1600 MHz",
                            Sound = "Stereo speakers, two microphones",
                            Webcam = "15 MPX",
                            Weight = "4.41 lbs",
                            WirelessController = "Intel Dual Band Wireless-AC 7260",
                            WirelessProtocol = "802.11a/b/g/n/ac, Bluetooth 4.0, NFC"
                        },
                        new
                        {
                            ProductDetailId = 8,
                            AudioCodec = "Realtek ALC3661",
                            Backlight = "Yes",
                            BaterryCells = "6-cell",
                            BatterySize = "91 Wh",
                            Bluetooth = "4.0",
                            CacheSize = "6 MB",
                            CacheType = "L3 cache",
                            CardReaderSupport = "SD Memory Card, SDHC Memory Card, SDIO, SDXC UHS Memory Card",
                            CardReaderType = "3 in 1 card reader",
                            ChipsetType = "Mobile Intel HM87 Express",
                            Cpu = "Intel Core i7 (4th Gen) 4712HQ / 2.3 GHz",
                            CpuSpeed = "3.3 GHz",
                            Dimensions = "15.6 in",
                            DisplayResolution = "3200 x 1800 (QHD+)",
                            DisplaySize = "39.6 cm",
                            DisplayTech = "WLED backlight",
                            DisplayType = "LED QHD+",
                            Features = "Intel Turbo Boost Technology 2.0",
                            GraphicName = "NVIDIA GeForce GT 750M",
                            GraphicSize = "4 GB",
                            HardDriveSize = "1 TB",
                            HardDriveType = "SSD",
                            ImgUrl1 = "https://cnet3.cbsistatic.com/img/KEM_0EsoAP-9kOds2Fbal9Ww540=/1200x675/2017/08/14/ec0fa893-faf2-46c3-8933-6898773804ba/apple-macbook-air-2017-05.jpg",
                            ImgUrl2 = "https://icdn2.digitaltrends.com/image/digitaltrends/macbook-air-2020-02.jpg",
                            ImgUrl3 = "https://cdn.mos.cms.futurecdn.net/HvjfsxzQHCZxpUYTVgyBDM.jpg",
                            InputType = "keyboard, touchpad",
                            Mainboard = "Mobile Intel HM87 Express",
                            Manufacturer = "Dell, Inc.",
                            Name = "MacbookAir 13",
                            NumCores = "Quad-Core",
                            OperatingSystem = "Windows 10 64-bit Edition",
                            ProductId = 8,
                            RamSize = "2 x 8 GB",
                            RamType = "DDR3L SDRAM 1600 MHz",
                            Sound = "Stereo speakers, two microphones",
                            Webcam = "15 MPX",
                            Weight = "4.41 lbs",
                            WirelessController = "Intel Dual Band Wireless-AC 7260",
                            WirelessProtocol = "802.11a/b/g/n/ac, Bluetooth 4.0, NFC"
                        },
                        new
                        {
                            ProductDetailId = 9,
                            AudioCodec = "Realtek ALC3661",
                            Backlight = "Yes",
                            BaterryCells = "6-cell",
                            BatterySize = "91 Wh",
                            Bluetooth = "4.0",
                            CacheSize = "6 MB",
                            CacheType = "L3 cache",
                            CardReaderSupport = "SD Memory Card, SDHC Memory Card, SDIO, SDXC UHS Memory Card",
                            CardReaderType = "3 in 1 card reader",
                            ChipsetType = "Mobile Intel HM87 Express",
                            Cpu = "Intel Core i7 (4th Gen) 4712HQ / 2.3 GHz",
                            CpuSpeed = "3.3 GHz",
                            Dimensions = "15.6 in",
                            DisplayResolution = "3200 x 1800 (QHD+)",
                            DisplaySize = "39.6 cm",
                            DisplayTech = "WLED backlight",
                            DisplayType = "LED QHD+",
                            Features = "Intel Turbo Boost Technology 2.0",
                            GraphicName = "NVIDIA GeForce GT 750M",
                            GraphicSize = "4 GB",
                            HardDriveSize = "1 TB",
                            HardDriveType = "SSD",
                            ImgUrl1 = "https://cdn.mos.cms.futurecdn.net/UwsmVJaCfuRHBUnrLeN2XP.jpg",
                            ImgUrl2 = "https://laptopmedia.com/wp-content/uploads/2019/11/lenovothinkpadx1extremegen2featured.jpg",
                            ImgUrl3 = "https://i.redd.it/wy0nuwcxjfi31.jpg",
                            InputType = "keyboard, touchpad",
                            Mainboard = "Mobile Intel HM87 Express",
                            Manufacturer = "Dell, Inc.",
                            Name = "LENOVO ThinkPad X1",
                            NumCores = "Quad-Core",
                            OperatingSystem = "Windows 10 64-bit Edition",
                            ProductId = 9,
                            RamSize = "2 x 8 GB",
                            RamType = "DDR3L SDRAM 1600 MHz",
                            Sound = "Stereo speakers, two microphones",
                            Webcam = "15 MPX",
                            Weight = "4.41 lbs",
                            WirelessController = "Intel Dual Band Wireless-AC 7260",
                            WirelessProtocol = "802.11a/b/g/n/ac, Bluetooth 4.0, NFC"
                        });
                });

            modelBuilder.Entity("ecommerce.Model.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("productId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("productImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("productInformation")
                        .HasColumnType("TEXT");

                    b.Property<string>("productName")
                        .HasColumnType("TEXT");

                    b.Property<double>("productPrice")
                        .HasColumnType("REAL");

                    b.Property<int>("quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("CartId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("ecommerce.Model.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address2")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fullname")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHashed")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("Zip4")
                        .HasColumnType("TEXT");

                    b.Property<string>("Zip5")
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address1 = "8200 broadway st",
                            Address2 = "apt 711n",
                            City = "houston",
                            DateCreated = new DateTime(2020, 4, 24, 13, 54, 13, 87, DateTimeKind.Local).AddTicks(3054),
                            Email = "wolnguyen98@gmail.com",
                            Fullname = "thuy nguyen",
                            LastLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHashed = "85UPoIIFby6fy3zmyv6A1i3Ql/vWS/fm6dPSIAA4E0Q=",
                            PasswordSalt = new byte[] { 126, 0, 129, 32, 94, 237, 68, 93, 28, 48, 51, 120, 133, 48, 197, 88 },
                            State = "tx",
                            Zip4 = "",
                            Zip5 = ""
                        },
                        new
                        {
                            CustomerId = 2,
                            Address1 = "8956 Sage St",
                            Address2 = "",
                            City = "Benton Harbor",
                            DateCreated = new DateTime(2020, 4, 24, 13, 54, 13, 91, DateTimeKind.Local).AddTicks(1623),
                            Email = "cmphan7@gmail.com",
                            Fullname = "cuong phan",
                            LastLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHashed = "85UPoIIFby6fy3zmyv6A1i3Ql/vWS/fm6dPSIAA4E0Q=",
                            PasswordSalt = new byte[] { 126, 0, 129, 32, 94, 237, 68, 93, 28, 48, 51, 120, 133, 48, 197, 88 },
                            State = "MI",
                            Zip4 = "",
                            Zip5 = "49022"
                        },
                        new
                        {
                            CustomerId = 3,
                            Address1 = "457 Illinois Road",
                            Address2 = "",
                            City = "Monsey",
                            DateCreated = new DateTime(2020, 4, 24, 13, 54, 13, 91, DateTimeKind.Local).AddTicks(1673),
                            Email = "kimnguyen137@gmail.com",
                            Fullname = "kim nguyen",
                            LastLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHashed = "85UPoIIFby6fy3zmyv6A1i3Ql/vWS/fm6dPSIAA4E0Q=",
                            PasswordSalt = new byte[] { 126, 0, 129, 32, 94, 237, 68, 93, 28, 48, 51, 120, 133, 48, 197, 88 },
                            State = "ny",
                            Zip4 = "",
                            Zip5 = "10952"
                        });
                });

            modelBuilder.Entity("ecommerce.Model.CustomerShippingAddresses", b =>
                {
                    b.Property<int>("ShippingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address2")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("Zip4")
                        .HasColumnType("TEXT");

                    b.Property<string>("Zip5")
                        .HasColumnType("TEXT");

                    b.HasKey("ShippingId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerShippingAddresses");

                    b.HasData(
                        new
                        {
                            ShippingId = 1,
                            Address1 = "8220 broadway",
                            Address2 = "apt 711n",
                            City = "houston",
                            CustomerId = 1,
                            Name = "thuy nguyen",
                            State = "tx",
                            Zip4 = "1233",
                            Zip5 = "77061"
                        },
                        new
                        {
                            ShippingId = 2,
                            Address1 = "8220 broadway",
                            Address2 = "apt 709n",
                            City = "houston",
                            CustomerId = 1,
                            Name = "chau nguyen",
                            State = "tx",
                            Zip4 = "1233",
                            Zip5 = "77061"
                        },
                        new
                        {
                            ShippingId = 3,
                            Address1 = "921 Trucklemans Lane",
                            Address2 = "",
                            City = "Brookfield",
                            CustomerId = 2,
                            Name = "cuong nguyen",
                            State = "ca",
                            Zip4 = "",
                            Zip5 = "665501"
                        },
                        new
                        {
                            ShippingId = 4,
                            Address1 = "8956 Sage St",
                            Address2 = "",
                            City = "Benton Harbor",
                            CustomerId = 2,
                            Name = "cuong phan",
                            State = "MI ",
                            Zip4 = "",
                            Zip5 = "49022"
                        },
                        new
                        {
                            ShippingId = 5,
                            Address1 = "339 East Thompson Court",
                            Address2 = "",
                            City = "Beaver Falls",
                            CustomerId = 3,
                            Name = "kim phan",
                            State = "PA ",
                            Zip4 = "",
                            Zip5 = "15010"
                        },
                        new
                        {
                            ShippingId = 6,
                            Address1 = "457 Illinois Road",
                            Address2 = "218 Village Road",
                            City = "Brookfield",
                            CustomerId = 3,
                            Name = "kim nguyen",
                            State = "ca",
                            Zip4 = "",
                            Zip5 = "665501"
                        });
                });

            modelBuilder.Entity("ecommerce.Model.OrderDetails", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SalePrice")
                        .HasColumnType("REAL");

                    b.HasKey("DetailId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("ecommerce.Model.Orders", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfItems")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderName")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderShipAddress1")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderShipAddress2")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderShipCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderShipState")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderShipZip4")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderShipZip5")
                        .HasColumnType("TEXT");

                    b.Property<double>("OrderTotal")
                        .HasColumnType("REAL");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ecommerce.Model.Products", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductInformation")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("REAL");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductImageUrl = "https://i.dell.com/sites/csimages/Video_Imagery/all/xps_7590_touch.png",
                            ProductInformation = "The world’s smallest 15.6-inch performance laptop with a stunning OLED display option. Now featuring 9th Gen Intel® Core™ processors.",
                            ProductName = "Dell XPS 15",
                            ProductPrice = 1399.0
                        },
                        new
                        {
                            ProductId = 2,
                            ProductImageUrl = "http://pngimg.com/uploads/macbook/macbook_PNG76.png",
                            ProductInformation = "The world’s smallest 15.6-inch performance laptop with a stunning OLED display option. Now featuring 9th Gen Intel® Core™ processors.",
                            ProductName = "Macbook Pro 2020",
                            ProductPrice = 1999.0
                        },
                        new
                        {
                            ProductId = 3,
                            ProductImageUrl = "https://i.ibb.co/8Kx8JkM/spectre.png",
                            ProductInformation = "The world’s smallest 15.6-inch performance laptop with a stunning OLED display option. Now featuring 9th Gen Intel® Core™ processors.",
                            ProductName = "HP Spectre X360 15",
                            ProductPrice = 1849.0
                        },
                        new
                        {
                            ProductId = 4,
                            ProductImageUrl = "https://i.ibb.co/pvv6H0G/asus.png",
                            ProductInformation = "The world’s smallest 15.6-inch performance laptop with a stunning OLED display option. Now featuring 9th Gen Intel® Core™ processors.",
                            ProductName = "ASUS GL702 Gamming",
                            ProductPrice = 1499.0
                        },
                        new
                        {
                            ProductId = 5,
                            ProductImageUrl = "https://i.ibb.co/cD5QTZ5/hpgame.png",
                            ProductInformation = "The world’s smallest 15.6-inch performance laptop with a stunning OLED display option. Now featuring 9th Gen Intel® Core™ processors.",
                            ProductName = "HP Gaming Pavilion",
                            ProductPrice = 999.0
                        },
                        new
                        {
                            ProductId = 6,
                            ProductImageUrl = "https://static.acer.com/up/Resource/Acer/Laptops/Swift_7/Photogallery/20190322/Acer-Swift-7-SF714-52T-Black-photogallery-02.png",
                            ProductInformation = "The world’s smallest 15.6-inch performance laptop with a stunning OLED display option. Now featuring 9th Gen Intel® Core™ processors.",
                            ProductName = "Acer Swift 7",
                            ProductPrice = 1799.0
                        },
                        new
                        {
                            ProductId = 7,
                            ProductImageUrl = "https://i.ibb.co/zxf2JHh/alien.png",
                            ProductInformation = "The world’s smallest 15.6-inch performance laptop with a stunning OLED display option. Now featuring 9th Gen Intel® Core™ processors.",
                            ProductName = "Dell Alienware 17",
                            ProductPrice = 2999.0
                        },
                        new
                        {
                            ProductId = 8,
                            ProductImageUrl = "https://i.ibb.co/4gypLd8/macair.png",
                            ProductInformation = "The world’s smallest 15.6-inch performance laptop with a stunning OLED display option. Now featuring 9th Gen Intel® Core™ processors.",
                            ProductName = "Macbook Air 13",
                            ProductPrice = 1299.0
                        },
                        new
                        {
                            ProductId = 9,
                            ProductImageUrl = "https://i.ibb.co/Cm5F0fD/lenovo.png",
                            ProductInformation = "The world’s smallest 15.6-inch performance laptop with a stunning OLED display option. Now featuring 9th Gen Intel® Core™ processors.",
                            ProductName = "LENOVO Thinkpad X1",
                            ProductPrice = 1719.0
                        });
                });

            modelBuilder.Entity("ecommerce.Data.ProductDetails", b =>
                {
                    b.HasOne("ecommerce.Model.Products", "Products")
                        .WithMany("productDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ecommerce.Model.Cart", b =>
                {
                    b.HasOne("ecommerce.Model.Customer", "Customer")
                        .WithMany("Cart")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ecommerce.Model.CustomerShippingAddresses", b =>
                {
                    b.HasOne("ecommerce.Model.Customer", "Customer")
                        .WithMany("CustomerShippingAddresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ecommerce.Model.OrderDetails", b =>
                {
                    b.HasOne("ecommerce.Model.Orders", "Orders")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ecommerce.Model.Orders", b =>
                {
                    b.HasOne("ecommerce.Model.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
